"""create strategy_tags table

Revision ID: 825b5db30024
Revises: 
Create Date: 2025-11-23 01:34:18.768054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825b5db30024'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_tags_id'), 'strategy_tags', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_tags_trade_id'), 'strategy_tags', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_tags_trade_id'), table_name='strategy_tags')
    op.drop_index(op.f('ix_strategy_tags_id'), table_name='strategy_tags')
    op.drop_table('strategy_tags')
    # ### end Alembic commands ###
